/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkRouteImport } from './routes/work'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OauthHandoffRouteImport } from './routes/oauth-handoff'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PortfolioSongsRouteImport } from './routes/portfolio.songs'
import { Route as PortfolioClipsRouteImport } from './routes/portfolio.clips'
import { Route as PortfolioAdsRouteImport } from './routes/portfolio.ads'
import { Route as IframeOauthStartRouteImport } from './routes/iframe-oauth.start'
import { Route as IframeOauthCallbackRouteImport } from './routes/iframe-oauth.callback'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminSocialsRouteImport } from './routes/admin.socials'
import { Route as AdminSignInRouteImport } from './routes/admin.sign-in'
import { Route as AdminSessionRouteImport } from './routes/admin.session'
import { Route as AdminServicesRouteImport } from './routes/admin.services'
import { Route as AdminSeoRouteImport } from './routes/admin.seo'
import { Route as AdminPagesRouteImport } from './routes/admin.pages'
import { Route as AdminFaqRouteImport } from './routes/admin.faq'
import { Route as AdminAboutRouteImport } from './routes/admin.about'
import { Route as ApiAdminTableRouteImport } from './routes/api.admin.table'

const WorkRoute = WorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => rootRouteImport,
} as any)
const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthHandoffRoute = OauthHandoffRouteImport.update({
  id: '/oauth-handoff',
  path: '/oauth-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PortfolioSongsRoute = PortfolioSongsRouteImport.update({
  id: '/portfolio/songs',
  path: '/portfolio/songs',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioClipsRoute = PortfolioClipsRouteImport.update({
  id: '/portfolio/clips',
  path: '/portfolio/clips',
  getParentRoute: () => rootRouteImport,
} as any)
const PortfolioAdsRoute = PortfolioAdsRouteImport.update({
  id: '/portfolio/ads',
  path: '/portfolio/ads',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeOauthStartRoute = IframeOauthStartRouteImport.update({
  id: '/iframe-oauth/start',
  path: '/iframe-oauth/start',
  getParentRoute: () => rootRouteImport,
} as any)
const IframeOauthCallbackRoute = IframeOauthCallbackRouteImport.update({
  id: '/iframe-oauth/callback',
  path: '/iframe-oauth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSocialsRoute = AdminSocialsRouteImport.update({
  id: '/socials',
  path: '/socials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSignInRoute = AdminSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSessionRoute = AdminSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicesRoute = AdminServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeoRoute = AdminSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPagesRoute = AdminPagesRouteImport.update({
  id: '/pages',
  path: '/pages',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqRoute = AdminFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAboutRoute = AdminAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AdminRoute,
} as any)
const ApiAdminTableRoute = ApiAdminTableRouteImport.update({
  id: '/api/admin/table',
  path: '/api/admin/table',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-handoff': typeof OauthHandoffRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/iframe-oauth/callback': typeof IframeOauthCallbackRoute
  '/iframe-oauth/start': typeof IframeOauthStartRoute
  '/portfolio/ads': typeof PortfolioAdsRoute
  '/portfolio/clips': typeof PortfolioClipsRoute
  '/portfolio/songs': typeof PortfolioSongsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/table': typeof ApiAdminTableRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-handoff': typeof OauthHandoffRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/iframe-oauth/callback': typeof IframeOauthCallbackRoute
  '/iframe-oauth/start': typeof IframeOauthStartRoute
  '/portfolio/ads': typeof PortfolioAdsRoute
  '/portfolio/clips': typeof PortfolioClipsRoute
  '/portfolio/songs': typeof PortfolioSongsRoute
  '/admin': typeof AdminIndexRoute
  '/api/admin/table': typeof ApiAdminTableRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/oauth-handoff': typeof OauthHandoffRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/testimonials': typeof TestimonialsRoute
  '/work': typeof WorkRoute
  '/admin/about': typeof AdminAboutRoute
  '/admin/faq': typeof AdminFaqRoute
  '/admin/pages': typeof AdminPagesRoute
  '/admin/seo': typeof AdminSeoRoute
  '/admin/services': typeof AdminServicesRoute
  '/admin/session': typeof AdminSessionRoute
  '/admin/sign-in': typeof AdminSignInRoute
  '/admin/socials': typeof AdminSocialsRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/iframe-oauth/callback': typeof IframeOauthCallbackRoute
  '/iframe-oauth/start': typeof IframeOauthStartRoute
  '/portfolio/ads': typeof PortfolioAdsRoute
  '/portfolio/clips': typeof PortfolioClipsRoute
  '/portfolio/songs': typeof PortfolioSongsRoute
  '/admin/': typeof AdminIndexRoute
  '/api/admin/table': typeof ApiAdminTableRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/oauth-handoff'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/work'
    | '/admin/about'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/session'
    | '/admin/sign-in'
    | '/admin/socials'
    | '/admin/testimonials'
    | '/iframe-oauth/callback'
    | '/iframe-oauth/start'
    | '/portfolio/ads'
    | '/portfolio/clips'
    | '/portfolio/songs'
    | '/admin/'
    | '/api/admin/table'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/faq'
    | '/oauth-handoff'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/work'
    | '/admin/about'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/session'
    | '/admin/sign-in'
    | '/admin/socials'
    | '/admin/testimonials'
    | '/iframe-oauth/callback'
    | '/iframe-oauth/start'
    | '/portfolio/ads'
    | '/portfolio/clips'
    | '/portfolio/songs'
    | '/admin'
    | '/api/admin/table'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/faq'
    | '/oauth-handoff'
    | '/services'
    | '/sitemap.xml'
    | '/testimonials'
    | '/work'
    | '/admin/about'
    | '/admin/faq'
    | '/admin/pages'
    | '/admin/seo'
    | '/admin/services'
    | '/admin/session'
    | '/admin/sign-in'
    | '/admin/socials'
    | '/admin/testimonials'
    | '/iframe-oauth/callback'
    | '/iframe-oauth/start'
    | '/portfolio/ads'
    | '/portfolio/clips'
    | '/portfolio/songs'
    | '/admin/'
    | '/api/admin/table'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  OauthHandoffRoute: typeof OauthHandoffRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TestimonialsRoute: typeof TestimonialsRoute
  WorkRoute: typeof WorkRoute
  IframeOauthCallbackRoute: typeof IframeOauthCallbackRoute
  IframeOauthStartRoute: typeof IframeOauthStartRoute
  PortfolioAdsRoute: typeof PortfolioAdsRoute
  PortfolioClipsRoute: typeof PortfolioClipsRoute
  PortfolioSongsRoute: typeof PortfolioSongsRoute
  ApiAdminTableRoute: typeof ApiAdminTableRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/work': {
      id: '/work'
      path: '/work'
      fullPath: '/work'
      preLoaderRoute: typeof WorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth-handoff': {
      id: '/oauth-handoff'
      path: '/oauth-handoff'
      fullPath: '/oauth-handoff'
      preLoaderRoute: typeof OauthHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/portfolio/songs': {
      id: '/portfolio/songs'
      path: '/portfolio/songs'
      fullPath: '/portfolio/songs'
      preLoaderRoute: typeof PortfolioSongsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/clips': {
      id: '/portfolio/clips'
      path: '/portfolio/clips'
      fullPath: '/portfolio/clips'
      preLoaderRoute: typeof PortfolioClipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portfolio/ads': {
      id: '/portfolio/ads'
      path: '/portfolio/ads'
      fullPath: '/portfolio/ads'
      preLoaderRoute: typeof PortfolioAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-oauth/start': {
      id: '/iframe-oauth/start'
      path: '/iframe-oauth/start'
      fullPath: '/iframe-oauth/start'
      preLoaderRoute: typeof IframeOauthStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iframe-oauth/callback': {
      id: '/iframe-oauth/callback'
      path: '/iframe-oauth/callback'
      fullPath: '/iframe-oauth/callback'
      preLoaderRoute: typeof IframeOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/socials': {
      id: '/admin/socials'
      path: '/socials'
      fullPath: '/admin/socials'
      preLoaderRoute: typeof AdminSocialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sign-in': {
      id: '/admin/sign-in'
      path: '/sign-in'
      fullPath: '/admin/sign-in'
      preLoaderRoute: typeof AdminSignInRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/session': {
      id: '/admin/session'
      path: '/session'
      fullPath: '/admin/session'
      preLoaderRoute: typeof AdminSessionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/services': {
      id: '/admin/services'
      path: '/services'
      fullPath: '/admin/services'
      preLoaderRoute: typeof AdminServicesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seo': {
      id: '/admin/seo'
      path: '/seo'
      fullPath: '/admin/seo'
      preLoaderRoute: typeof AdminSeoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pages': {
      id: '/admin/pages'
      path: '/pages'
      fullPath: '/admin/pages'
      preLoaderRoute: typeof AdminPagesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faq': {
      id: '/admin/faq'
      path: '/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AdminFaqRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/about': {
      id: '/admin/about'
      path: '/about'
      fullPath: '/admin/about'
      preLoaderRoute: typeof AdminAboutRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/admin/table': {
      id: '/api/admin/table'
      path: '/api/admin/table'
      fullPath: '/api/admin/table'
      preLoaderRoute: typeof ApiAdminTableRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAboutRoute: typeof AdminAboutRoute
  AdminFaqRoute: typeof AdminFaqRoute
  AdminPagesRoute: typeof AdminPagesRoute
  AdminSeoRoute: typeof AdminSeoRoute
  AdminServicesRoute: typeof AdminServicesRoute
  AdminSessionRoute: typeof AdminSessionRoute
  AdminSignInRoute: typeof AdminSignInRoute
  AdminSocialsRoute: typeof AdminSocialsRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAboutRoute: AdminAboutRoute,
  AdminFaqRoute: AdminFaqRoute,
  AdminPagesRoute: AdminPagesRoute,
  AdminSeoRoute: AdminSeoRoute,
  AdminServicesRoute: AdminServicesRoute,
  AdminSessionRoute: AdminSessionRoute,
  AdminSignInRoute: AdminSignInRoute,
  AdminSocialsRoute: AdminSocialsRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  OauthHandoffRoute: OauthHandoffRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TestimonialsRoute: TestimonialsRoute,
  WorkRoute: WorkRoute,
  IframeOauthCallbackRoute: IframeOauthCallbackRoute,
  IframeOauthStartRoute: IframeOauthStartRoute,
  PortfolioAdsRoute: PortfolioAdsRoute,
  PortfolioClipsRoute: PortfolioClipsRoute,
  PortfolioSongsRoute: PortfolioSongsRoute,
  ApiAdminTableRoute: ApiAdminTableRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
